name: Checks

on:
  pull_request:
    branches: main
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  format:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun format:check
  lint:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun lint:check
  lint-markdown:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://avtodev/markdown-lint:v1
        with:
          config: '.markdownlint.json'
          args: '.'
  typecheck:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun typecheck
  test:
    uses: ./.github/workflows/run-check.yaml
    with:
      # TODO: why I need explicitly specifying fetch main branch here?
      command: git fetch origin main:main && bun test
