name: Publish

on:
  push:
    branches: main
    paths: src/articles/**/*.md

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Cannot use run-check as getting secrets fails that way
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: canary
      - run: bun install
      - run: |
          touch .env
          echo HASHNODE_URL=${{ vars.HASHNODE_URL }} >> .env
            echo HASHNODE_PUBLICATION_ID=${{ secrets.HASHNODE_PUBLICATION_ID }} >> .env
          echo HASHNODE_TOKEN=${{ secrets.HASHNODE_TOKEN }} >> .env
          echo DEV_TO_KEY=${{ secrets.DEV_TO_KEY }} >> .env
          echo MEDIUM_AUTHOR_ID=${{ vars.MEDIUM_AUTHOR_ID }} >> .env
          echo MEDIUM_INTEGRATION_TOKEN=${{ secrets.MEDIUM_INTEGRATION_TOKEN }} >> .env
          echo SUPABASE_URL=${{ vars.SUPABASE_URL }} >> .env
          echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> .env
          echo SUPABASE_STORAGE_BUCKET=${{ vars.SUPABASE_STORAGE_BUCKET }} >> .env
      - run: bun publish
